### ISSUE TITLE
Erro in WHMCS 7.8.3

### ISSUE THREAD

**Issue by menigma2** [limestonenetworks/oneportal-whmcs#19]
After filling in as import information and ordering the import begins or error described below.

Exception: String could not be parsed as XML in /home/MY_USER/public_html/MY_WHMCS/modules/addons/opserverimport/opserverimport.php:182
Stack trace:
#0 /home/MY_USER/public_html/MY_WHMCS/modules/addons/opserverimport/opserverimport.php(182): SimpleXMLElement->__construct(' #1 /home/MY_USER/public_html/MY_WHMCS/admin/addonmodules.php(0): opserverimport_output(Array)
#2 {main}

**Comment by logan2211** [comment]
The XML validity issue with the products feed should be resolved now. Please re-open this if the problem is still occurring.
