### ISSUE TITLE
Deprecation of updateusage.php

### ISSUE THREAD

**Issue by sclaeys** [limestonenetworks/oneportal-whmcs#9]
Please remove the usageupdate.cron.php file from oneportal-whmcs/oneportal directory as this file is not compatible with any modern WHMCS installations.

**Comment by tabp0le** [comment]
I was wondering why this stopped working. 🤣 How are we supposed to get usage stats now?

**Comment by radwebhosting** [comment]
Usage stats are now gathered through bwgraph function called every hour from oneportal.php

**Comment by sclaeys** [comment]
@tabp0le are you having an issue with importing the usage statistics in WHMCS?

**Comment by tabp0le** [comment]
Yeah they stopped working completely.

**Comment by montross50** [comment]
#15
